name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v4

    - name: Install Git LFS
      run: |
        sudo apt-get update
        sudo apt-get install -y git-lfs
        git lfs install

    - name: Set up Hugging Face Git credentials
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Clean previous hf_space if exists
      run: |
        rm -rf hf_space

    - name: Clone Hugging Face Space
      run: |
        git clone https://huggingface_hub:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/${{ secrets.HF_SPACE_ID }} hf_space

    - name: Copy project files into Space
      run: |
        mkdir -p hf_space/models
        rsync -av --progress --exclude='.git' --exclude='hf_space' ./ hf_space/
        cp models/labels.json hf_space/models/

    - name: Commit and push to Hugging Face
      run: |
        cd hf_space
        git add .
        git commit -m "🤖 Auto-update from GitHub main branch" || echo "No changes to commit"
        git push