name: Deploy to Hugging Face Spaces

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Clone this repo
        uses: actions/checkout@v4

      - name: 🤖 Set up Git (inside HF Space)
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: 🚀 Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_SPACE_ID: ${{ secrets.HF_SPACE_ID }}
        run: |
          # Fresh clone of Hugging Face Space
          git clone https://huggingface_hub:${HF_TOKEN}@huggingface.co/spaces/${HF_SPACE_ID} hf_space

          # Clean destination (optional if HF repo is messy)
          rm -rf hf_space/*

          # Copy all project files into HF Space folder
          cp -r * hf_space/
          cp -r .[^.]* hf_space/ || true   # Copy hidden files like .gitignore, ignoring errors

          # Commit and push
          cd hf_space
          git add .
          git commit -m "🤖 Auto-update from GitHub main branch"
          git push